### ISSUE TITLE
Issue #22 still seen in `master` branch

### ISSUE THREAD

**Issue by vsawal** [DMTF/YANG-to-Redfish-Converter#29]
#22
The fix is available in `yang-plugin` branch.

Error:
```
(py3) vsawal@W109PQB7H2:~/dmtf/YANG-to-Redfish-Converter$ pyang --plugindir ./YANG-to-Redfish-Plugin --format redfish --path ~/dmtf/public --target_dir ~/dmtf/yang_to_rf_csdl/ ~/dmtf/public/release/models/vlan/openconfig-vlan.yang
Uhh
Traceback (most recent call last):
  File "/home/vsawal/python-virtual-envs/py3/bin/pyang", line 450, in <module>
    run()
  File "/home/vsawal/python-virtual-envs/py3/bin/pyang", line 419, in run
    emit_obj.emit(ctx, modules, fd)
  File "./YANG-to-Redfish-Plugin/redfish.py", line 66, in emit
    xml_root = csdltree.build_tree(module, list_of_xml, logger)
  File "./YANG-to-Redfish-Plugin/rf/csdltree.py", line 145, in build_tree
    build_tree_repeat(item, schema_node, entity_node, main_node, list_of_xml, logger, prefix + csdlname + '.', topleveltypes=topleveltypes, toplevelimports=toplevelimports)
  File "./YANG-to-Redfish-Plugin/rf/csdltree.py", line 335, in build_tree_repeat
    annotation = handlers.handle_generic(yang_keyword, yang_arg, yang_children, target)
  File "./YANG-to-Redfish-Plugin/rf/statement_handlers.py", line 22, in handle_generic
    target, {'Term': redfishtypes.get_descriptive_properties_mapping(yang_keyword),
  File "./YANG-to-Redfish-Plugin/rf/redfishtypes.py", line 57, in get_descriptive_properties_mapping
    target_name = get_valid_csdl_identifier(property_name)
  File "./YANG-to-Redfish-Plugin/rf/redfishtypes.py", line 33, in get_valid_csdl_identifier
    new_name = name.replace('-', '_').replace(':', '.').replace('"', '').replace('\'', '')
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by vsawal** [comment]
Branch `yang-plugin` merged into `master`. 
Verified.
