### ISSUE TITLE
Travis error - unexpected close tag

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#45]
CSDL files generated with YANG-2019 branch.  The  CSDL appears well formed, but this message occurs for some of the generated file.

```
(TF-Network)$ > npm test > output
(node:23028) UnhandledPromiseRejectionWarning: Error: http://redfish.dmtf.org/schemas/v1/openconfig_lldp_v1.xml: http://redfish.dmtf.org/schemas/v1/openconfig_lldp_types_v1.xml: Unexpected close tag
Line: 52
Column: 7
Char: >
    at error (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\sax\lib\sax.js:677:7)
    at closeTag (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\sax\lib\sax.js:871:9)
    at SAXParser.write (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\sax\lib\sax.js:1436:13)
    at new XmlDocument (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\xmldoc\lib\xmldoc.js:261:15)
    at Metadata.parse (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\Metadata.js:34:13)
    at C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\cache\csdlCache.js:28:14
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:23028) UnhandledPromiseRejectionWarning: Error: http://redfish.dmtf.org/schemas/v1/rfc7223/ietf_interfaces_v1.xml: Unexpected close tag
Line: 52
Column: 7
Char: >
    at error (C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\sax\lib\sax.js:651:10)
```

**Comment by jcleung5549** [comment]
From Tomas: 
So that particular error is part of a non-disclosed error by the `npm test` scripts.

Basically, any particular file that isn't found in the `metadata` folder is attempted to grab from the internet.  "http://redfish.dmtf.org/schemas/v1/openconfig_lldp_v1.xml" is not a real file, so it gets a 404 document but still tries to verify it.  I can look into how to surpress this exception.

**Comment by jcleung5549** [comment]
Aug 2 meeting - Need to also convert the referenced files.  In the above case, openconfig_lldp_types_v1.xml needs to be generated.

**Comment by jcleung5549** [comment]
Output from converting all the referenced openconfig files.  A couple of errors messages in front, then the remainder is as-expected.

```
$ pyang -p yangs --plugindir ./YANG-to-Redfish-Plugin --format redfish --target_dir output_dir --combine_all_nodes yangs/*
yangs/openconfig-network-instance-policy.yang:12: error: module "openconfig-routing-policy" not found in search path
yangs/openconfig-platform-transceiver.yang:14: error: module "openconfig-transport-types" not found in search path
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: aggregation-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: aggregation-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: ipv4-address
new TYPE:: ipv4-address-zoned
new TYPE:: ipv6-address
new TYPE:: ipv6-address-zoned
new TYPE:: ipv4-prefix
new TYPE:: ipv6-prefix
new TYPE:: ip-address
new TYPE:: ip-prefix
new TYPE:: ip-version
new TYPE:: domain-name
new TYPE:: host
new TYPE:: as-number
new TYPE:: dscp
new TYPE:: ipv6-flow-label
new TYPE:: port-number
new TYPE:: uri
new TYPE:: url
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: base-interface-ref
new TYPE:: interface-id
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: lacp-activity-type
new TYPE:: lacp-timeout-type
new TYPE:: lacp-synchronization-type
new TYPE:: lacp-period-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: chassis-id-type
new TYPE:: port-id-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: local-defined-next-hop
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: network-instance-ref
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: route-distinguisher
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: port-num-range
new TYPE:: ip-protocol-type
new TYPE:: ethertype-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: component-power-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: match-set-options-type
new TYPE:: match-set-options-restricted-type
new TYPE:: tag-type
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: queue-behavior
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: percentage
new TYPE:: std-regexp
new TYPE:: timeticks64
new TYPE:: ieeefloat32
new TYPE:: routing-password
new TYPE:: stat-interval
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
new TYPE:: vlan-id
new TYPE:: vlan-range
new TYPE:: qinq-id
new TYPE:: qinq-id-range
new TYPE:: vlan-mode-type
new TYPE:: vlan-ref
We don't recognize keyword ('openconfig-extensions', 'openconfig-version'), create as statement
Success writing file to disk: output_dir/openconfig_acl_v1.xml
Success writing file to disk: output_dir/openconfig_alarm_types_v1.xml
Success writing file to disk: output_dir/openconfig_extensions_v1.xml
Success writing file to disk: output_dir/openconfig_if_aggregate_v1.xml
Success writing file to disk: output_dir/openconfig_if_aggregate_v1.xml
Success writing file to disk: output_dir/openconfig_if_ethernet_v1.xml
Success writing file to disk: output_dir/openconfig_if_types_v1.xml
Success writing file to disk: output_dir/openconfig_inet_types_v1.xml
Success writing file to disk: output_dir/openconfig_interfaces_v1.xml
Success writing file to disk: output_dir/openconfig_lacp_v1.xml
Success writing file to disk: output_dir/openconfig_lldp_v1.xml
Success writing file to disk: output_dir/openconfig_lldp_types_v1.xml
Success writing file to disk: output_dir/openconfig_local_routing_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_l2_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_l2_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_l3_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_policy_v1.xml
Success writing file to disk: output_dir/openconfig_network_instance_types_v1.xml
Success writing file to disk: output_dir/openconfig_packet_match_v1.xml
Success writing file to disk: output_dir/openconfig_packet_match_types_v1.xml
Success writing file to disk: output_dir/openconfig_platform_v1.xml
Success writing file to disk: output_dir/openconfig_platform_cpu_v1.xml
Success writing file to disk: output_dir/openconfig_platform_ext_v1.xml
Success writing file to disk: output_dir/openconfig_platform_fan_v1.xml
Success writing file to disk: output_dir/openconfig_platform_linecard_v1.xml
Success writing file to disk: output_dir/openconfig_platform_port_v1.xml
Success writing file to disk: output_dir/openconfig_platform_psu_v1.xml
Success writing file to disk: output_dir/openconfig_platform_transceiver_v1.xml
Success writing file to disk: output_dir/openconfig_platform_types_v1.xml
Success writing file to disk: output_dir/openconfig_policy_types_v1.xml
Success writing file to disk: output_dir/openconfig_qos_v1.xml
Success writing file to disk: output_dir/openconfig_qos_elements_v1.xml
Success writing file to disk: output_dir/openconfig_qos_interfaces_v1.xml
Success writing file to disk: output_dir/openconfig_qos_types_v1.xml
Success writing file to disk: output_dir/openconfig_types_v1.xml
Success writing file to disk: output_dir/openconfig_vlan_v1.xml
Success writing file to disk: output_dir/openconfig_vlan_v1.xml
Success writing file to disk: output_dir/openconfig_vlan_types_v1.xml
Success writing file to disk: output_dir/openconfig_yang_types_v1.xml
Success writing file to disk: output_dir/iana_if_type_v1.xml
Success writing file to disk: output_dir/ietf_interfaces_v1.xml
Success writing file to disk: output_dir/ietf_ip_v1.xml
Success writing file to disk: output_dir/ietf_system_v1.xml
```

**Comment by jcleung5549** [comment]
Attaching output from running Travis

[output.txt](https://github.com/DMTF/YANG-to-Redfish-Converter/files/3487240/output.txt)

**Comment by jcleung5549** [comment]
Using the branch yang-2019 , this error is no longer seen.
