### ISSUE TITLE
Travis errors in openconfig_acl_v1.xml

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#47]
3 Error messages
- Unable to locate type
- Unable to locate annotation term
- Pascal case violation

 ```
13) CSDL Tests
       metadata/openconfig_acl_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_pkt_match_types.ethertype_type"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:420:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:402:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:93:64)

  14) CSDL Tests
       metadata/openconfig_acl_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_pkt_match_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:516:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:98:51)

  15) CSDL Tests
       metadata/openconfig_acl_v1.xml
         Properties are Pascal-cased:
     Error: Property Name "interface" is not Pascal-cased
      at checkPropertiesPascalCased (node_modules\redfishrepotest\csdl-syntax-test.js:537:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:102:50)
```

**Comment by jcleung5549** [comment]
With the yang-2019 branch, the error messages are down to 2:

```
 1) CSDL Tests
       metadata/openconfig_acl_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_pkt_match_types.ethertype_type"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

  2) CSDL Tests
       metadata/openconfig_acl_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_pkt_match_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)
```

**Comment by jcleung5549** [comment]
Issue resolved in latest update to the emulator.
