### ISSUE TITLE
Travis errors on openconfig_if_aggregate_v1.xml

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#48]
2 Errors
- Invalid enum member name
- Property not Pascal case

```
  19) CSDL Tests
       metadata/openconfig_if_aggregate_v1.xml
         Enum Members are valid names:
     Error: Enum member "aggregation_type" of EnumType YangTypes is invalid!
      at checkEnumMembers (node_modules\redfishrepotest\csdl-syntax-test.js:527:15)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:99:49)

  20) CSDL Tests
       metadata/openconfig_if_aggregate_v1.xml
         Properties are Pascal-cased:
     Error: Property Name "lag_type" is not Pascal-cased
      at checkPropertiesPascalCased (node_modules\redfishrepotest\csdl-syntax-test.js:537:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:102:50)
```

**Comment by mraineri** [comment]
These are more things we'll need to whitelist in Travis. Can't enforce the enum and property naming rules for these types of files.

**Comment by jcleung5549** [comment]
Can you give me a pointer to the the whitelist?  I will modify locally so Travis will complete without errors.

**Comment by jcleung5549** [comment]
Using branch yang-2019, there are no errors on openconfig_if_aggregate_v1.xml.
