### ISSUE TITLE
Travis error - Unknown attribute name Alias (3 times)

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#49]
```
42) CSDL Tests
       metadata/openconfig_network_instance_l2_v1.xml
         "before all" hook:
     Uncaught Error: Unknown attribute name Alias
      at Annotation.parseAttribute (node_modules\CSDLParser\lib\ParserCommon.js:77:13)
      at Annotation.parseEntity (node_modules\CSDLParser\lib\ParserCommon.js:30:12)
      at Annotation.init (node_modules\CSDLParser\lib\ParserCommon.js:14:12)
      at new Annotation (node_modules\CSDLParser\lib\Annotation.js:22:10)
      at Schema.parseChildElement (node_modules\CSDLParser\lib\ParserCommon.js:72:28)
      at C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\ParserCommon.js:26:10
      at XmlElement.eachChild (node_modules\xmldoc\lib\xmldoc.js:97:20)
      at Schema.parseEntity (node_modules\CSDLParser\lib\ParserCommon.js:25:13)
      at Schema.init (node_modules\CSDLParser\lib\ParserCommon.js:14:12)
      at new Schema (node_modules\CSDLParser\lib\Schema.js:26:10)
      at C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\Metadata.js:74:27
      at XmlElement.eachChild (node_modules\xmldoc\lib\xmldoc.js:97:20)
      at Metadata.parseDataServices (node_modules\CSDLParser\lib\Metadata.js:69:13)
      at C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\Metadata.js:52:23
      at XmlDocument.XmlElement.eachChild (node_modules\xmldoc\lib\xmldoc.js:97:20)
      at Metadata.parse (node_modules\CSDLParser\lib\Metadata.js:41:9)
      at Object.module.exports.parseMetadata (node_modules\CSDLParser\lib\Metadata.js:97:10)
      at C:\Users\jcleung\Documents\GitHub External\branch-networktf\Redfish\node_modules\CSDLParser\lib\Metadata.js:121:20
      at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by jcleung5549** [comment]
Same Error message from
- openconfig_qos_elements_v1.xml
- openconfig_qos_interfaces_v1.xml

**Comment by jcleung5549** [comment]
Using branch yang-2019, error messages still exist

**Comment by jcleung5549** [comment]
Issue resolved in latest update to the emulator.
