### ISSUE TITLE
Travis warning - Complex Types Should Not have Permissions (5 times)

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#50]
Error occurs in 5 files:
- openconfig_network_instance_v1.xml
- openconfig_platform_transceiver_v1.xml
- openconfig_platform_v1.xml
- openconfig_qos_v1.xml
- openconfig_vlan_v1.xml

```
 6) CSDL Tests
       metadata/openconfig_network_instance_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_vlan_types.vlan_id"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

 8) CSDL Tests
       metadata/openconfig_platform_transceiver_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "openconfig_platform.v1_0_0.present"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

9) CSDL Tests
       metadata/openconfig_platform_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_opt_types.frequency_type"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

13) CSDL Tests
       metadata/openconfig_qos_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_qos_types.queue_behavior"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

15) CSDL Tests
       metadata/openconfig_vlan_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "openconfig_network_instance.v1_0_0.status"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)
```

**Comment by jcleung5549** [comment]
Issue resolved in latest update to the emulator.
