### ISSUE TITLE
Travis error - Unable to locate type (6 times)

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#51]
This error was generated by 6 files
- openconfig_acl_v1.xml looking for oc_pkt_match_types.ethertype_type
- openconfig_interfaces_v1.xml looking for oc_vlan_types.vlan_id
- openconfig_platform_transceiver_v1.xml looking for openconfig_platform.v1_0_0.present
- openconfig_platform_v1.xml looking for oc_opt_types.frequency_type
- openconfig_qos_v1.xml looking for oc_qos_types.queue_behavior
- openconfig_vlan_v1.xml looking for openconfig_network_instance.v1_0_0.status

```
1) CSDL Tests
       metadata/openconfig_acl_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_pkt_match_types.ethertype_type"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

3) CSDL Tests
       metadata/openconfig_interfaces_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "openconfig_if_ethernet.v1_0_0.duplex_mode"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

 6) CSDL Tests
       metadata/openconfig_network_instance_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_vlan_types.vlan_id"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

  8) CSDL Tests
       metadata/openconfig_platform_transceiver_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "openconfig_platform.v1_0_0.present"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

  9) CSDL Tests
       metadata/openconfig_platform_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_opt_types.frequency_type"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

 13) CSDL Tests
       metadata/openconfig_qos_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "oc_qos_types.queue_behavior"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)

15) CSDL Tests
       metadata/openconfig_vlan_v1.xml
         Complex Types Should Not Have Permissions:
     Error: Unable to locate type "openconfig_network_instance.v1_0_0.status"
      at checkComplexTypePermissionsInSchema (node_modules\redfishrepotest\csdl-syntax-test.js:452:15)
      at complexTypesPermissions (node_modules\redfishrepotest\csdl-syntax-test.js:434:5)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:106:64)
```

**Comment by jcleung5549** [comment]
Issue resolved in latest update to the emulator.
