### ISSUE TITLE
Travis error - Unable to locate annotation (5 times)

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#52]
This error was generated from 5 files
- openconfig_acl_v1.xml looking for oc_pkt_match_types.YangType
- openconfig_interfaces_v1.xml looking for oc_vlan_types.YangType
- openconfig_network_instance_v1.xml looking for oc_vlan_types.YangType
- openconfig_platform_v1.xml looking for oc_opt_types.YangType
- openconfig_qos_v1.xml looking for oc_qos_types.YangType

```
2) CSDL Tests
       metadata/openconfig_acl_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_pkt_match_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)
 
4) CSDL Tests
       metadata/openconfig_interfaces_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_vlan_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)

 7) CSDL Tests
       metadata/openconfig_network_instance_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_vlan_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)

 10) CSDL Tests
       metadata/openconfig_platform_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_opt_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)

 14) CSDL Tests
       metadata/openconfig_qos_v1.xml
         All Annotation Terms are valid:
     Error: Unable to locate annotation term "oc_qos_types.YangType"
      at checkAnnotationTerms (node_modules\redfishrepotest\csdl-syntax-test.js:566:13)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:112:51)
```

**Comment by jcleung5549** [comment]
Issue resolved in latest update to the emulator.
