### ISSUE TITLE
Travis error - RedfishYangExtensions.v1_0_0 needs OwningEntity and Release terms

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/YANG-to-Redfish-Converter#53]
```
16) CSDL Tests
       metadata/RedfishYangExtensions_v1.xml
         All namespaces have OwningEntity:
     Error: Namespace RedfishYangExtensions.v1_0_0 lacks OwningEntity!
      at schemaOwningEntityCheck (node_modules\redfishrepotest\csdl-syntax-test.js:1530:15)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:124:55)

17) CSDL Tests
       metadata/RedfishYangExtensions_v1.xml
         All versioned, non-errata namespaces have Release:
     Error: Namespace RedfishYangExtensions.v1_0_0 lacks Release term!
      at schemaReleaseCheck (node_modules\redfishrepotest\csdl-syntax-test.js:1555:15)
      at Context.it (node_modules\redfishrepotest\csdl-syntax-test.js:136:72)
```

**Comment by mraineri** [comment]
Since that file is constructed manually, I think we need to add those annotations to the file.

**Comment by jcleung5549** [comment]
Added annotations.
